// LOCALHOST
GET http://localhost:8080/contacts

###

// Tanner
GET http://localhost:8080/contacts/626c561d9ac0754e737cd68c

###

// Tony
GET http://localhost:8080/contacts/626c561d9ac0754e737cd68d

###

// Peter
GET http://localhost:8080/contacts/626c561d9ac0754e737cd68e

###

// PRODUCTION Deploy
GET https://cse341-node-w02personal.herokuapp.com/contacts

###

GET https://cse341-node-w02personal.herokuapp.com/contacts/626c561d9ac0754e737cd68c

###

GET https://cse341-node-w02personal.herokuapp.com/contacts/626c561d9ac0754e737cd68d

###

GET https://cse341-node-w02personal.herokuapp.com/contacts/626c561d9ac0754e737cd68e

###

// Adding, Updating, and Deleting contacts

// Adding
POST http://localhost:8080/contacts HTTP/1.1
content-type: application/json

{
    "firstName": "Bruce",
    "lastName": "Banner",
    "email": "smashingstuff22@email.com",
    "favoriteColor": "green",
    "birthday": "12/19/1969"
}

###

// Updating
PUT http://localhost:8080/contacts/626c561d9ac0754e737cd68d HTTP/1.1
content-type: application/json

{
    "firstName": "Tony",
    "lastName": "Stark",
    "email": "ironman22@email.com",
    "favoriteColor": "gold",
    "birthday": "05/29/70"
}

###

// Deleting
DELETE http://localhost:8080/contacts/626c561d9ac0754e737cd68c HTTP/1.1
content-type: application/json

{
    "firstName": "Tanner"
}

###

// PRODUCTION Deploy

POST https://cse341-node-w02personal.herokuapp.com/contacts HTTP/1.1
content-type: application/json

{
    "firstName": "Bruce",
    "lastName": "Banner",
    "email": "smashingstuff22@email.com",
    "favoriteColor": "green",
    "birthday": "12/19/1969"
}

###

PUT https://cse341-node-w02personal.herokuapp.com/contacts/626c561d9ac0754e737cd68d HTTP/1.1
content-type: application/json

{
    "firstName": "Tony",
    "lastName": "Stark",
    "email": "ironman22@email.com",
    "favoriteColor": "gold",
    "birthday": "05/29/70"
}

###

DELETE https://cse341-node-w02personal.herokuapp.com/contacts/626c561d9ac0754e737cd68c HTTP/1.1
content-type: application/json

{
    "firstName": "Tanner"
}